// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuCPZOhdi7tpAhGwIRbILkFa4PIyo76QM',
    appId: '1:990784231254:web:ed9c49c822ba20c88168f7',
    messagingSenderId: '990784231254',
    projectId: 'temperatures-measurement',
    authDomain: 'temperatures-measurement.firebaseapp.com',
    databaseURL: 'https://temperatures-measurement-default-rtdb.firebaseio.com',
    storageBucket: 'temperatures-measurement.firebasestorage.app',
    measurementId: 'G-C7VL1R9MQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8tebMweWIPVMVw5MY8-XbAMLosHqiHHI',
    appId: '1:990784231254:android:f5c81173ce0510fc8168f7',
    messagingSenderId: '990784231254',
    projectId: 'temperatures-measurement',
    databaseURL: 'https://temperatures-measurement-default-rtdb.firebaseio.com',
    storageBucket: 'temperatures-measurement.firebasestorage.app',
  );
}
